### ISSUE TITLE
How ~ input list format ??

### ISSUE THREAD

**Issue by peternara** [wujiyang/Triplet-Loss#1]
hi. @wujiyang 

in face_triplet_train.prototxt 
> .source: "/media/wujiyang/data/FaceData/train.txt" 

I want to know format in train.txt

**Comment by wujiyang** [comment]
@peternara  The format in train.txt is just as same as which in normal classification job. 
for example:
path/1_1.jpg  0
path/1_2.jpg  0
path/2_1.jpg  1
path/2_2.jpg  1
......
path/....jpg    n

**Comment by peternara** [comment]
@wujiyang thank very much~~
